### ISSUE TITLE
internal.json has exact enter dates for Forgotten Realms, Midnight Hunt and Crimson Vow but the API does not show them

### ISSUE THREAD

**Issue by bakert** [glacials/whatsinstandard#198] opened 2021-06-06 14:47 UTC
(Thanks for creating this resource – it's super useful to us in the Penny Dreadful community which rotates on Standard-legal set release.)

Forgotten Realms is present at https://whatsinstandard.com/api/v6/standard.json but has `enterDate.exact` of `null`. Midnight Hunt and Crimson Vow are missing entirely. All the right info is in internal.json.

Presumably some build/deploy step needs to be performed?

Could this be automated upon merge to main? It seems to happen quite a lot. I'm volunteering to do the work to make that happen if someone wants to point me in the right direction.

**Comment by silasary** [comment] 2021-06-23 02:00
@glacials Can you look into this?

**Comment by glacials** [comment] 2021-06-25 19:24
Sorry for the late reply, I've been very busy with life! The build/deploy step has been automated for years but looks like something broke, and I can confirm the last deployed build is incorrect. I'm looking into this now and will post back here with an update.

**Comment by glacials** [comment] 2021-06-25 21:38
The deploy pipeline is now fixed, more resilient to breakages like this in the future, and will also now notify me immediately if a deploy fails. It is still automated to happen on every push/merge to `main`. Thanks for reporting the issue and sorry for the delay in response!

**Closed by glacials** 2021-06-25 21:38 UTC

**Comment by bakert** [comment] 2021-06-25 21:40
Woohoo. 🙏 thanks!
